---
- name: intalling and launching Metricbeat
  hosts: webservers
  become: yes
  tasks:

  - name: download Metricbeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

  - name: install metricbeat deb
    command: sudo dpkg -i metricbeat-7.6.1-amd64.deb

  - name: drop in metricbeat.yml
    copy:
     src: /etc/ansible/metricbeat-config.yml
     dest: /etc/metricbeat/metricbeat.yml

  - name: enable and configure system module for metricbeat
    command: sudo metricbeat modules enable docker

  - name: set up metricbeat
    command: sudo metricbeat setup

  - name: start metricbeat service
    command: sudo service metricbeat start

  - name: enable service metricbeat on boot
    systemd:
     name: metricbeat
     enabled: yes
